version: '3.4'

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  api:
    # image: andretr/smartbear-anguphy-api:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    depends_on:
      - postgres
    ports:
      - "8000:8000"
  